name: Assign PR Author

on:
  pull_request:
    types: [opened]

jobs:
  assign-author:
    runs-on: ubuntu-latest

    steps:
      - name: Assign PR author
        uses: kentaro-m/auto-assign-action@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.event.pull_request.user.login }}
