name: PR Welcome
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr-open-greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/check-user-permission@v2
        id: isTeamMember
        with:
          require: 'write'
          username: ${{ github.event.pull_request.user.login }}

      - uses: actions-awesome/pr-helper@1.1.1
        with:
          actions: 'add-assignees, add-reviewers, greeting, add-labels'
          assignees: 'warmthsea'
          reviewers: 'warmthsea'
          labels: 'Contribution::Community'
          token: ${{ github.token }}
          pr-number: ${{ github.event.pull_request.number }}
          greeting-message: 'Hello %user%, thank you for contributing to %repo%, please see our [guideline](%guideline%) to see how to make contribution'
          greeting-guideline-address: 'https://github.com/warmthsea/mark-pr-label-test/blob/main/CONTRIBUTING.md'

      - name: Add Assignees' Avatars
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Assignees:**
            ${{ join(fromJson(steps.isTeamMember.outputs.assign-members), '\n - @') }}
